language:
  - ruby

gemfile:
  - .travis.gemfile
  - .travis.gemfile.rubyracer

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-2
  - jruby-19mode

matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: .travis.gemfile.rubyracer

  include:
    - rvm: jruby-19mode
      gemfile: .travis.gemfile.rubyrhino
