language:
  - ruby

gemfile:
  - .travis.gemfile
  - .travis.gemfile.rubyracer

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode

matrix:
  exclude:
    - rvm: jruby-18mode
      gemfile: .travis.gemfile.rubyracer
    - rvm: jruby-19mode
      gemfile: .travis.gemfile.rubyracer

  include:
    - rvm: jruby-18mode
      gemfile: .travis.gemfile.rubyrino
    - rvm: jruby-19mode
      gemfile: .travis.gemfile.rubyrino